---
apiVersion: "kind.x-k8s.io/v1alpha4"
kind: Cluster
name: local
nodes:
  - role: control-plane
networking:
  serviceSubnet: "10.12.0.0/16"
  podSubnet: "10.112.0.0/16"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["http://registry-dockerio:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.io".tls]
      insecure_skip_verify = true
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
      endpoint = ["http://registry-quayio:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."quay.io".tls]
      insecure_skip_verify = true
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://registry-gcrio:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."gcr.io".tls]
      insecure_skip_verify = true
