version: "3.9"
services:
  mirror-docker.io:
    image: registry:2
    restart: always
    networks:
    - kind
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://mirror.gcr.io

  mirror-quay.io:
    image: registry:2
    restart: always
    networks:
    - kind
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://quay.io

  mirror-gcr.io:
    image: registry:2
    restart: always
    networks:
    - kind
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://gcr.io

  mirror-k8s.gcr.io:
    image: registry:2
    restart: always
    networks:
    - kind
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://k8s.gcr.io

  mirror-ghcr.io:
    image: registry:2
    restart: always
    networks:
    - kind
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://ghcr.io

networks:
  kind:
    external:
      name: kind
